services:
  test:
    build:
      context: .
    env_file:
      - .env.test
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py test -v 2 --settings=theatre_service.settings_test"
    depends_on:
      - test_db

  test_db:
    image: postgres:alpine3.20
    restart: always
    env_file:
      - .env.test
    ports:
      - $POSTGRES_EXTERNAL_PORT:$POSTGRES_PORT
