# Generated by Django 4.2.14 on 2024-07-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_actor_genre_performance_reservation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ("-show_time",)},
        ),
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ("-title",)},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
    ]
