# Generated by Django 4.2.14 on 2024-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_performance_options_alter_play_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="play_image_path"),
        ),
    ]
