# Generated by Django 4.2.14 on 2024-07-29 20:43

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.models.create_image_path
            ),
        ),
    ]
